BlackJackApp.MVC/Controllers/GameController.cs
using BlackJackApp.ViewModels.GameModels;
using System.Threading.Tasks;
using System.Web.Mvc;
using BlackJackApp.Services.Interfaces;

namespace BlackJackApp.Controllers.Controllers
{
    public class GameController : Controller
    {
        private IGameService _gameService;

        public GameController(IGameService gameService)
        {
            _gameService = gameService;
        }

        public async Task<ActionResult> Start()
        {
            var names = await _gameService.GetPlayers();
            return View(names.Users);
        }

        public async Task<ActionResult> CreateGame(CreateGameView viewModel)
        {
            var gameId = await _gameService.Create(viewModel);
            return RedirectToAction("Play", new { id = gameId, param = 2 });
        }

        public async Task<ActionResult> Play(int id, GetCardOption param)
        {
            ModelState.Clear();
            var result = await _gameService.Play(id, param);
            if ((result.IsResultComplete && param == GetCardOption.Start) || GetCardOption.Enough == param)
            {
                return View("GameFinnished", result);
            }
            if (!result.IsResultComplete && param == GetCardOption.Start)
            {
                return View("CurrentGame", result);
            }
            if (result.IsResultComplete && GetCardOption.Take == param)
            {
                return Json(new
                {
                    id = id,
                    result = result.IsResultComplete,
                    url = Url.Action("Play", "Game", new { id = id, param = 1 })
                });
            }

            if (!result.IsResultComplete && GetCardOption.Take == param)
            {
                return PartialView("CreateNextRoundForPlayers", result);
            }

            return View("Error");
        }
    }
}

BlackJackApp.MVC/Controllers/HistoryController.cs
using BlackJackApp.Services.Interfaces;
using BlackJackApp.ViewModels.HistoryModels;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BlackJackApp.Controllers.Controllers
{
    public class HistoryController : Controller
    {
        IHistoryService _historyService;

        public HistoryController(IHistoryService historyService)
        {
            _historyService = historyService;
        }
        
        public async Task<ActionResult> Details(int id)
        {
            var result = await _historyService.Details(id);

            return View(result);
        }

        public async Task<ActionResult> ShowHistoryGrid()
        {
            return View("HistoryGrid");
        }

        public async Task<string> GetGames(int offset = 0)
        {
            var games = new GetGamesHistoryView();
            string json = string.Empty;
            if (offset == 0)
            {
                games = await _historyService.GetGames(offset: 0);
                json = JsonConvert.SerializeObject(games.Games);
                return json;
            }       
            games = await _historyService.GetGames(offset);

            json = JsonConvert.SerializeObject(games.Games);
            return json;
        }
    }
}

BlackJackApp.MVC/Views/Game/CreateNextRoundForDealer.cshtml
@model BlackJackApp.ViewModels.GameModels.PlayGameView
<link href="@Url.Content("~/Content/Flexes.css")" rel="stylesheet" type="text/css" />
<ul class="flex-container">
    @foreach (var round in Model.Users)
    {
        if (round.UserName == "Dealer")
        {
            <div class="flex-item">
                <div>@round.UserName</div>
                <div>Points: @round.CardSum</div>
                @foreach (var card in round.Cards)
                {
                    <ul>@card.Rank / @card.Suit</ul>
                }
            </div>
        }
    }
</ul>

BlackJackApp.MVC/Views/Game/CreateNextRoundForPlayers.cshtml
@model BlackJackApp.ViewModels.GameModels.PlayGameView
<link href="@Url.Content("~/Content/Flexes.css")" rel="stylesheet" type="text/css" />
<ul class="flex-container">
    @foreach (var round in Model.Users)
    {
        if (round.UserName != "Dealer")
        {
            <div class="flex-item">
                <div>@round.UserName</div>
                <div>Points: @round.CardSum</div>
                @foreach (var card in round.Cards)
                {
                    <ul>@card.Rank / @card.Suit</ul>
                }
            </div>
        }
    }
</ul>

BlackJackApp.MVC/Views/Game/CurrentGame.cshtml
@model BlackJackApp.ViewModels.GameModels.PlayGameView
<link href="@Url.Content("~/Content/Flexes.css")" rel="stylesheet" type="text/css" />

<div style="text-align:right">
    <div id="playerTable">
        @{Html.RenderPartial("CreateNextRoundForPlayers", Model);}
    </div>

    <div id="dealerTable">
        @{Html.RenderPartial("CreateNextRoundForDealer", Model);}
    </div>
</div>
<div class="curGame" id="enough" style="text-align:center">
    @using (Html.BeginForm("Play", "Game", FormMethod.Post))
    {
        @Html.Hidden("id", Model.GameId);
        GetCardOption enough = GetCardOption.Enough;
        @Html.Hidden("param", enough);

        <div id="result">
            @Html.HiddenFor(r => Model.IsResultComplete)
        </div>
        <input type="submit" value="enough" id="takeButton" />
    }
</div>
<div class="curGame" id="take" style="text-align:center">
    @using (Ajax.BeginForm("Play", "Game", new AjaxOptions
    {
        UpdateTargetId = "playerTable",
        HttpMethod = "Post",
        OnSuccess = "OnSuccess",
    }))
    {

        @Html.Hidden("id", Model.GameId);
        @Html.HiddenFor(r => Model.IsResultComplete);

        GetCardOption take = GetCardOption.Take;
        @Html.Hidden("param", take);

        <input type="submit" value="take" id="enoughButton" />
    }
</div>
@Scripts.Render("~/bundles/StartGameView/current-game")
@Scripts.Render("~/bundles/jquery")

BlackJackApp.MVC/Views/Game/GameFinnished.cshtml
@model BlackJackApp.ViewModels.GameModels.PlayGameView
<link href="@Url.Content("~/Content/Flexes.css")" rel="stylesheet" type="text/css" />
<ul class="flex-container">
    @foreach (var round in Model.Users)
    {
        <div class="flex-item">
            <div>@round.UserName</div>
            <div>Points: @round.CardSum</div>
            @foreach (var card in round.Cards)
            {
                <ul>@card.Rank/ @card.Suit</ul>
            }
            @if (round.UserName != "Dealer")
            {
                <div>Status: @round.PlayerStatus</div>
            }
        </div>
    }
</ul>

<div style="text-align:center">
    @using (Html.BeginForm("ShowGames",
                "History"))
    {
        <input type="submit" value="Go to history" id="toHistory" />
    }
</div>
<div style="text-align:center">
    @using (Html.BeginForm("Start",
            "Game"))
    {
        <input type="submit" value="Finish" id="toStart" />
    }
</div>

@Scripts.Render("~/bundles/StartGameView/game-finished")

BlackJackApp.MVC/Views/Game/Start.cshtml
<form action="~/Game/CreateGame" method="post" id="form">
    <ul id="fieldList">
        <li style="text-align:center">
            <h4><label for="name">Start Game </label></h4>
            <input type="text" id="name" name="PlayerName" class="k-textbox"  placeholder="Enter your name..." style="width: 220px;" />
        </li>
        <li style="text-align:center">
            <input id="dropElementId" name="BotQuantity" />
        </li>
        <li style="text-align:center">
            <button id="startbutton" type="button">Press to start</button>
        </li>
    </ul>
</form>

@Scripts.Render("~/bundles/StartGameView/start-game")

BlackJackApp.MVC/Views/History/Details.cshtml
<link href="@Url.Content("~/Content/Flexes.css")" rel="stylesheet" type="text/css" />
<ul class="flex-container">
    @foreach (var user in Model.HistoryDetails)
    {

        <div class="flex-item">
            <div>@user.UserName</div>
            @foreach (var card in user.Cards)
            {
                <ul>@card.Rank / @card.Suit</ul>
            }
                <div>Sum of Cards: @user.CardSum</div>
            @if (user.UserName != "Dealer")
            {

                <div>Status: @user.Status</div>
            }
        </div>
    }
</ul>

BlackJackApp.MVC/Views/History/HistoryGrid.cshtml
<div id="grid"></div>
@Scripts.Render("~/bundles/HistoryView/history-grid")

BlackJackApp.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/BlackJack.css")" rel="stylesheet" type="text/css" />

    <link href="https://kendo.cdn.telerik.com/2016.3.914/styles/kendo.common-material.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2016.3.914/styles/kendo.material.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2016.3.914/styles/kendo.dataviz.material.min.css" rel="stylesheet" type="text/css" />

    <script src="https://kendo.cdn.telerik.com/2016.3.914/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2016.3.914/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2016.3.914/js/kendo.aspnetmvc.min.js"></script>
</head>

<body>
    <div class="container-fluid">
        <div class="row k-header" style="text-align:left">
            <h1>Black Jack App</h1>
            <h1>@Html.ActionLink("Start Game", "Start", "Game")</h1>
            <h1>@Html.ActionLink("History", "ShowHistoryGrid", "History")</h1>
        </div>
    </div>

    @RenderBody()
</body>
</html>